In [1]:
import os
# Find the latest version of spark 3.x  from http://www.apache.org/dist/spark/ and enter as the spark version
spark_version = 'spark-3.4.3'
os.environ['SPARK_VERSION']=spark_version

# Install Spark and Java
!apt-get update
!apt-get install openjdk-11-jdk-headless -qq > /dev/null
!wget -q http://www.apache.org/dist/spark/$SPARK_VERSION/$SPARK_VERSION-bin-hadoop3.tgz
!tar xf $SPARK_VERSION-bin-hadoop3.tgz
!pip install -q findspark

# Set Environment Variables
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-11-openjdk-amd64"
os.environ["SPARK_HOME"] = f"/content/{spark_version}-bin-hadoop3"

# Start a SparkSession
import findspark
findspark.init()

Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Hit:4 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:6 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:7 https://ppa.launchpadcontent.net/c2d4u.team/c2d4u4.0+/ubuntu jammy InRelease
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,389 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [2,160 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [51.5 kB]
Fetched 3,858 kB in 3s (1,381 kB/s)
Reading package lists... Done

In [2]:
# Import packages
from pyspark.sql import SparkSession
from pyspark.sql import Row
from pyspark.sql.types import StructType,StructField,StringType, DateType,IntegerType
from pyspark import SparkFiles

# Create a SparkSession
spark = SparkSession.builder.appName("TempViews").getOrCreate()

In [3]:
# Read the data from the csv on GitHub
from pyspark import SparkFiles
url = 'https://raw.githubusercontent.com/DKogge/project4/main/Resources/bank-additional-full.csv'
spark.sparkContext.addFile(url)


bank_additional_full = spark.read.option('header', 'true').csv(SparkFiles.get("bank-additional-full.csv"), inferSchema=True, sep=';', timestampFormat="mm/dd/yy")

# Show DataFrame
bank_additional_full.show()

+---+-----------+--------+-------------------+-------+-------+----+---------+-----+-----------+--------+--------+-----+--------+-----------+------------+--------------+-------------+---------+-----------+---+
|age|        job| marital|          education|default|housing|loan|  contact|month|day_of_week|duration|campaign|pdays|previous|   poutcome|emp.var.rate|cons.price.idx|cons.conf.idx|euribor3m|nr.employed|  y|
+---+-----------+--------+-------------------+-------+-------+----+---------+-----+-----------+--------+--------+-----+--------+-----------+------------+--------------+-------------+---------+-----------+---+
| 56|  housemaid| married|           basic.4y|     no|     no|  no|telephone|  may|        mon|     261|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 57|   services| married|        high.school|unknown|     no|  no|telephone|  may|        mon|     149|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 37|   services| married|        high.school|     no|    yes|  no|telephone|  may|        mon|     226|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 40|     admin.| married|           basic.6y|     no|     no|  no|telephone|  may|        mon|     151|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 56|   services| married|        high.school|     no|     no| yes|telephone|  may|        mon|     307|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 45|   services| married|           basic.9y|unknown|     no|  no|telephone|  may|        mon|     198|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 59|     admin.| married|professional.course|     no|     no|  no|telephone|  may|        mon|     139|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 41|blue-collar| married|            unknown|unknown|     no|  no|telephone|  may|        mon|     217|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 24| technician|  single|professional.course|     no|    yes|  no|telephone|  may|        mon|     380|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 25|   services|  single|        high.school|     no|    yes|  no|telephone|  may|        mon|      50|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 41|blue-collar| married|            unknown|unknown|     no|  no|telephone|  may|        mon|      55|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 25|   services|  single|        high.school|     no|    yes|  no|telephone|  may|        mon|     222|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 29|blue-collar|  single|        high.school|     no|     no| yes|telephone|  may|        mon|     137|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 57|  housemaid|divorced|           basic.4y|     no|    yes|  no|telephone|  may|        mon|     293|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 35|blue-collar| married|           basic.6y|     no|    yes|  no|telephone|  may|        mon|     146|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 54|    retired| married|           basic.9y|unknown|    yes| yes|telephone|  may|        mon|     174|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 35|blue-collar| married|           basic.6y|     no|    yes|  no|telephone|  may|        mon|     312|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 46|blue-collar| married|           basic.6y|unknown|    yes| yes|telephone|  may|        mon|     440|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 50|blue-collar| married|           basic.9y|     no|    yes| yes|telephone|  may|        mon|     353|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 39| management|  single|           basic.9y|unknown|     no|  no|telephone|  may|        mon|     195|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
+---+-----------+--------+-------------------+-------+-------+----+---------+-----+-----------+--------+--------+-----+--------+-----------+------------+--------------+-------------+---------+-----------+---+
only showing top 20 rows

In [4]:
 # Print our schema
bank_additional_full.printSchema()

root
 |-- age: integer (nullable = true)
 |-- job: string (nullable = true)
 |-- marital: string (nullable = true)
 |-- education: string (nullable = true)
 |-- default: string (nullable = true)
 |-- housing: string (nullable = true)
 |-- loan: string (nullable = true)
 |-- contact: string (nullable = true)
 |-- month: string (nullable = true)
 |-- day_of_week: string (nullable = true)
 |-- duration: integer (nullable = true)
 |-- campaign: integer (nullable = true)
 |-- pdays: integer (nullable = true)
 |-- previous: integer (nullable = true)
 |-- poutcome: string (nullable = true)
 |-- emp.var.rate: double (nullable = true)
 |-- cons.price.idx: double (nullable = true)
 |-- cons.conf.idx: double (nullable = true)
 |-- euribor3m: double (nullable = true)
 |-- nr.employed: double (nullable = true)
 |-- y: string (nullable = true)

In [5]:
# Fill Missing Values
bank_additional_filled = bank_additional_full.na.fill(0)

# Show DataFrame
bank_additional_filled.show()

+---+-----------+--------+-------------------+-------+-------+----+---------+-----+-----------+--------+--------+-----+--------+-----------+------------+--------------+-------------+---------+-----------+---+
|age|        job| marital|          education|default|housing|loan|  contact|month|day_of_week|duration|campaign|pdays|previous|   poutcome|emp.var.rate|cons.price.idx|cons.conf.idx|euribor3m|nr.employed|  y|
+---+-----------+--------+-------------------+-------+-------+----+---------+-----+-----------+--------+--------+-----+--------+-----------+------------+--------------+-------------+---------+-----------+---+
| 56|  housemaid| married|           basic.4y|     no|     no|  no|telephone|  may|        mon|     261|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 57|   services| married|        high.school|unknown|     no|  no|telephone|  may|        mon|     149|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 37|   services| married|        high.school|     no|    yes|  no|telephone|  may|        mon|     226|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 40|     admin.| married|           basic.6y|     no|     no|  no|telephone|  may|        mon|     151|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 56|   services| married|        high.school|     no|     no| yes|telephone|  may|        mon|     307|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 45|   services| married|           basic.9y|unknown|     no|  no|telephone|  may|        mon|     198|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 59|     admin.| married|professional.course|     no|     no|  no|telephone|  may|        mon|     139|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 41|blue-collar| married|            unknown|unknown|     no|  no|telephone|  may|        mon|     217|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 24| technician|  single|professional.course|     no|    yes|  no|telephone|  may|        mon|     380|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 25|   services|  single|        high.school|     no|    yes|  no|telephone|  may|        mon|      50|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 41|blue-collar| married|            unknown|unknown|     no|  no|telephone|  may|        mon|      55|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 25|   services|  single|        high.school|     no|    yes|  no|telephone|  may|        mon|     222|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 29|blue-collar|  single|        high.school|     no|     no| yes|telephone|  may|        mon|     137|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 57|  housemaid|divorced|           basic.4y|     no|    yes|  no|telephone|  may|        mon|     293|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 35|blue-collar| married|           basic.6y|     no|    yes|  no|telephone|  may|        mon|     146|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 54|    retired| married|           basic.9y|unknown|    yes| yes|telephone|  may|        mon|     174|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 35|blue-collar| married|           basic.6y|     no|    yes|  no|telephone|  may|        mon|     312|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 46|blue-collar| married|           basic.6y|unknown|    yes| yes|telephone|  may|        mon|     440|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 50|blue-collar| married|           basic.9y|     no|    yes| yes|telephone|  may|        mon|     353|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 39| management|  single|           basic.9y|unknown|     no|  no|telephone|  may|        mon|     195|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
+---+-----------+--------+-------------------+-------+-------+----+---------+-----+-----------+--------+--------+-----+--------+-----------+------------+--------------+-------------+---------+-----------+---+
only showing top 20 rows

In [6]:
bank_additional_filled.count()

41188

In [7]:
bank_additional_filled.createOrReplaceTempView('bank_additional_filled')

In [8]:
# To get the data for just Job, marital status and Education
query = """
SELECT job, marital, education
from bank_additional_filled
"""
spark.sql(query).show()

+-----------+--------+-------------------+
|        job| marital|          education|
+-----------+--------+-------------------+
|  housemaid| married|           basic.4y|
|   services| married|        high.school|
|   services| married|        high.school|
|     admin.| married|           basic.6y|
|   services| married|        high.school|
|   services| married|           basic.9y|
|     admin.| married|professional.course|
|blue-collar| married|            unknown|
| technician|  single|professional.course|
|   services|  single|        high.school|
|blue-collar| married|            unknown|
|   services|  single|        high.school|
|blue-collar|  single|        high.school|
|  housemaid|divorced|           basic.4y|
|blue-collar| married|           basic.6y|
|    retired| married|           basic.9y|
|blue-collar| married|           basic.6y|
|blue-collar| married|           basic.6y|
|blue-collar| married|           basic.9y|
| management|  single|           basic.9y|
+-----------+--------+-------------------+
only showing top 20 rows

In [9]:
# Get the count of customers per job category:
query ="""
SELECT job, COUNT(*) as count
FROM bank_additional_filled
GROUP BY job;
"""
spark.sql(query).show()

+-------------+-----+
|          job|count|
+-------------+-----+
|   management| 2924|
|      retired| 1720|
|      unknown|  330|
|self-employed| 1421|
|      student|  875|
|  blue-collar| 9254|
| entrepreneur| 1456|
|       admin.|10422|
|   technician| 6743|
|     services| 3969|
|    housemaid| 1060|
|   unemployed| 1014|
+-------------+-----+

In [10]:
# Find the average age of customers by marital status
query ="""
SELECT marital, AVG(age) as avg_age
FROM bank_additional_filled
GROUP BY marital;
"""
spark.sql(query).show()

+--------+-----------------+
| marital|          avg_age|
+--------+-----------------+
| unknown|           40.275|
|divorced|44.89939288811795|
| married|42.30716463414634|
|  single|33.15871369294606|
+--------+-----------------+

In [11]:
# Calls by day of the week
query="""
SELECT day_of_week, COUNT(*) AS number_of_calls
FROM bank_additional_filled
GROUP BY day_of_week
order by
case day_of_week
when 'mon' then 1
when 'tue' then 2
when 'wed' then 3
when 'thu' then 4
when 'fri' then 5 end;
"""
spark.sql(query).show()

+-----------+---------------+
|day_of_week|number_of_calls|
+-----------+---------------+
|        mon|           8514|
|        tue|           8090|
|        wed|           8134|
|        thu|           8623|
|        fri|           7827|
+-----------+---------------+

In [12]:
# Get the number of customers contacted during different months
query ="""
SELECT month, COUNT(*) as count
FROM bank_additional_filled
GROUP BY month;
"""
spark.sql(query).show()

+-----+-----+
|month|count|
+-----+-----+
|  jun| 5318|
|  aug| 6178|
|  may|13769|
|  mar|  546|
|  oct|  718|
|  jul| 7174|
|  nov| 4101|
|  apr| 2632|
|  dec|  182|
|  sep|  570|
+-----+-----+

In [13]:
# Rename the default column to `default credit` and show only this new column
df = bank_additional_filled
df = df.withColumnRenamed('default', 'default credit')
df.show()

+---+-----------+--------+-------------------+--------------+-------+----+---------+-----+-----------+--------+--------+-----+--------+-----------+------------+--------------+-------------+---------+-----------+---+
|age|        job| marital|          education|default credit|housing|loan|  contact|month|day_of_week|duration|campaign|pdays|previous|   poutcome|emp.var.rate|cons.price.idx|cons.conf.idx|euribor3m|nr.employed|  y|
+---+-----------+--------+-------------------+--------------+-------+----+---------+-----+-----------+--------+--------+-----+--------+-----------+------------+--------------+-------------+---------+-----------+---+
| 56|  housemaid| married|           basic.4y|            no|     no|  no|telephone|  may|        mon|     261|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 57|   services| married|        high.school|       unknown|     no|  no|telephone|  may|        mon|     149|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 37|   services| married|        high.school|            no|    yes|  no|telephone|  may|        mon|     226|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 40|     admin.| married|           basic.6y|            no|     no|  no|telephone|  may|        mon|     151|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 56|   services| married|        high.school|            no|     no| yes|telephone|  may|        mon|     307|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 45|   services| married|           basic.9y|       unknown|     no|  no|telephone|  may|        mon|     198|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 59|     admin.| married|professional.course|            no|     no|  no|telephone|  may|        mon|     139|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 41|blue-collar| married|            unknown|       unknown|     no|  no|telephone|  may|        mon|     217|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 24| technician|  single|professional.course|            no|    yes|  no|telephone|  may|        mon|     380|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 25|   services|  single|        high.school|            no|    yes|  no|telephone|  may|        mon|      50|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 41|blue-collar| married|            unknown|       unknown|     no|  no|telephone|  may|        mon|      55|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 25|   services|  single|        high.school|            no|    yes|  no|telephone|  may|        mon|     222|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 29|blue-collar|  single|        high.school|            no|     no| yes|telephone|  may|        mon|     137|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 57|  housemaid|divorced|           basic.4y|            no|    yes|  no|telephone|  may|        mon|     293|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 35|blue-collar| married|           basic.6y|            no|    yes|  no|telephone|  may|        mon|     146|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 54|    retired| married|           basic.9y|       unknown|    yes| yes|telephone|  may|        mon|     174|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 35|blue-collar| married|           basic.6y|            no|    yes|  no|telephone|  may|        mon|     312|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 46|blue-collar| married|           basic.6y|       unknown|    yes| yes|telephone|  may|        mon|     440|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 50|blue-collar| married|           basic.9y|            no|    yes| yes|telephone|  may|        mon|     353|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
| 39| management|  single|           basic.9y|       unknown|     no|  no|telephone|  may|        mon|     195|       1|  999|       0|nonexistent|         1.1|        93.994|        -36.4|    4.857|     5191.0| no|
+---+-----------+--------+-------------------+--------------+-------+----+---------+-----+-----------+--------+--------+-----+--------+-----------+------------+--------------+-------------+---------+-----------+---+
only showing top 20 rows

In [14]:
# Converting Pyspark DataFRame to Pandas DataFrame
import pandas as pd
pd.set_option('display.max_columns', None)
bank_marketing_df = df.toPandas()

#Show the DataFframe
bank_marketing_df.head()

,age,job,marital,education,default credit,housing,loan,contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,261,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,149,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,226,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,151,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,307,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [15]:
#Save the Dataframe to a csvFile
bank_marketing_df.to_csv('output.csv', index=False)

In [16]:
# Determine the number of unique values in each column.
bank_marketing_df.nunique()

age                 78
job                 12
marital              4
education            8
default credit       3
housing              3
loan                 3
contact              2
month               10
day_of_week          5
duration          1544
campaign            42
pdays               27
previous             8
poutcome             3
emp.var.rate        10
cons.price.idx      26
cons.conf.idx       26
euribor3m          316
nr.employed         11
y                    2
dtype: int64

In [17]:
bank_marketing_df = bank_marketing_df.drop(columns=['emp.var.rate', 'cons.price.idx', 'cons.conf.idx', 'euribor3m'])
bank_marketing_df.head()

,age,job,marital,education,default credit,housing,loan,contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,261,1,999,0,nonexistent,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,149,1,999,0,nonexistent,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,226,1,999,0,nonexistent,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,151,1,999,0,nonexistent,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,307,1,999,0,nonexistent,5191.0,no

In [18]:
 # Check the Job value counts to identify and replace with "Other"
bank_marketing_df['job'].value_counts()

job
admin.           10422
blue-collar       9254
technician        6743
services          3969
management        2924
retired           1720
entrepreneur      1456
self-employed     1421
housemaid         1060
unemployed        1014
student            875
unknown            330
Name: count, dtype: int64

In [19]:
# Choose a cutoff value and create a list of jobs to be replaced
# use the variable name `job_to_replace`
value_counts = bank_marketing_df['job'].value_counts()
job_to_replace = value_counts[value_counts < 1050].index

# Replace in dataframe
for jobs in job_to_replace:
  bank_marketing_df['job'] = bank_marketing_df['job'].replace(jobs,"Other")

# Check to make sure replacement was successful
bank_marketing_df['job'].value_counts()

job
admin.           10422
blue-collar       9254
technician        6743
services          3969
management        2924
Other             2219
retired           1720
entrepreneur      1456
self-employed     1421
housemaid         1060
Name: count, dtype: int64

In [20]:
# Check the value_counts
bank_marketing_df['marital'].value_counts()

marital
married     24928
single      11568
divorced     4612
unknown        80
Name: count, dtype: int64

In [21]:
# Check the value_counts
bank_marketing_df['education'].value_counts()

education
university.degree      12168
high.school             9515
basic.9y                6045
professional.course     5243
basic.4y                4176
basic.6y                2292
unknown                 1731
illiterate                18
Name: count, dtype: int64

In [22]:
# Generate our categorical variable lists and check the number of unique values in each column
bank_marketing_cat = bank_marketing_df.dtypes[bank_marketing_df.dtypes == "object"].index.tolist()
bank_marketing_df[bank_marketing_cat].nunique()

job               10
marital            4
education          8
default credit     3
housing            3
loan               3
contact            2
month             10
day_of_week        5
poutcome           3
y                  2
dtype: int64

In [23]:
# Convert categorical data to numeric with `pd.get_dummies`
bank_marketing_dummies_df = pd.get_dummies(bank_marketing_df, columns=['job', 'marital', 'education', 'default credit', 'housing', 'loan', 'contact', 'month', 'day_of_week', 'poutcome', 'y'], drop_first=True)
bank_marketing_dummies_df = bank_marketing_dummies_df.astype(int)
bank_marketing_dummies_df.head()

,age,duration,campaign,pdays,previous,nr.employed,job_admin.,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_technician,marital_married,marital_single,marital_unknown,education_basic.6y,education_basic.9y,education_high.school,education_illiterate,education_professional.course,education_university.degree,education_unknown,default credit_unknown,default credit_yes,housing_unknown,housing_yes,loan_unknown,loan_yes,contact_telephone,month_aug,month_dec,month_jul,month_jun,month_mar,month_may,month_nov,month_oct,month_sep,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_nonexistent,poutcome_success,y_yes
0,56,261,1,999,0,5191,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0
1,57,149,1,999,0,5191,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0
2,37,226,1,999,0,5191,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0
3,40,151,1,999,0,5191,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0
4,56,307,1,999,0,5191,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0

In [24]:
#shorten DF name
bank_df = bank_marketing_dummies_df.copy()
bank_df.head()

,age,duration,campaign,pdays,previous,nr.employed,job_admin.,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_technician,marital_married,marital_single,marital_unknown,education_basic.6y,education_basic.9y,education_high.school,education_illiterate,education_professional.course,education_university.degree,education_unknown,default credit_unknown,default credit_yes,housing_unknown,housing_yes,loan_unknown,loan_yes,contact_telephone,month_aug,month_dec,month_jul,month_jun,month_mar,month_may,month_nov,month_oct,month_sep,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,poutcome_nonexistent,poutcome_success,y_yes
0,56,261,1,999,0,5191,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0
1,57,149,1,999,0,5191,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0
2,37,226,1,999,0,5191,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0
3,40,151,1,999,0,5191,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0
4,56,307,1,999,0,5191,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0

In [25]:
# Import more dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf

In [26]:
# Split our preprocessed data into our features and target arrays
y = bank_df["y_yes"]
X = bank_df.drop(columns="y_yes")

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [27]:
# Create the StandardScaler instance
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [28]:
# Define the model  *** first iteration to set a baseline ***
number_input_features = (X_train.shape[1])
hidden_nodes_layer1 =  5
hidden_nodes_layer2 = 5

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 5)                 240

 dense_1 (Dense)             (None, 5)                 30

 dense_2 (Dense)             (None, 1)                 6

=================================================================
Total params: 276 (1.08 KB)
Trainable params: 276 (1.08 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [29]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [30]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
966/966 [==============================] - 3s 2ms/step - loss: 0.3426 - accuracy: 0.8629
Epoch 2/100
966/966 [==============================] - 2s 2ms/step - loss: 0.2064 - accuracy: 0.9040
Epoch 3/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1944 - accuracy: 0.9083
Epoch 4/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1911 - accuracy: 0.9094
Epoch 5/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1895 - accuracy: 0.9099
Epoch 6/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1876 - accuracy: 0.9117
Epoch 7/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1867 - accuracy: 0.9113
Epoch 8/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1859 - accuracy: 0.9122
Epoch 9/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1852 - accuracy: 0.9120
Epoch 10/100
966/966 [==============================] - 3s 3ms/step - loss: 0.1846 - accuracy: 0.9123
Epoch 11/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1840 - accuracy: 0.9127
Epoch 12/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1836 - accuracy: 0.9135
Epoch 13/100
966/966 [==============================] - 3s 3ms/step - loss: 0.1832 - accuracy: 0.9127
Epoch 14/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1827 - accuracy: 0.9132
Epoch 15/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1826 - accuracy: 0.9139
Epoch 16/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1821 - accuracy: 0.9130
Epoch 17/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1820 - accuracy: 0.9137
Epoch 18/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1813 - accuracy: 0.9143
Epoch 19/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1813 - accuracy: 0.9142
Epoch 20/100
966/966 [==============================] - 2s 3ms/step - loss: 0.1811 - accuracy: 0.9137
Epoch 21/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1807 - accuracy: 0.9144
Epoch 22/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1806 - accuracy: 0.9139
Epoch 23/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1802 - accuracy: 0.9146
Epoch 24/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1799 - accuracy: 0.9146
Epoch 25/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1799 - accuracy: 0.9149
Epoch 26/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1797 - accuracy: 0.9143
Epoch 27/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1792 - accuracy: 0.9141
Epoch 28/100
966/966 [==============================] - 3s 3ms/step - loss: 0.1791 - accuracy: 0.9149
Epoch 29/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1790 - accuracy: 0.9143
Epoch 30/100
966/966 [==============================] - 2s 3ms/step - loss: 0.1790 - accuracy: 0.9152
Epoch 31/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1785 - accuracy: 0.9148
Epoch 32/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1785 - accuracy: 0.9150
Epoch 33/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1786 - accuracy: 0.9148
Epoch 34/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1783 - accuracy: 0.9154
Epoch 35/100
966/966 [==============================] - 3s 3ms/step - loss: 0.1783 - accuracy: 0.9160
Epoch 36/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1782 - accuracy: 0.9152
Epoch 37/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1779 - accuracy: 0.9156
Epoch 38/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1780 - accuracy: 0.9148
Epoch 39/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1779 - accuracy: 0.9160
Epoch 40/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1780 - accuracy: 0.9155
Epoch 41/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1776 - accuracy: 0.9152
Epoch 42/100
966/966 [==============================] - 3s 3ms/step - loss: 0.1776 - accuracy: 0.9154
Epoch 43/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1776 - accuracy: 0.9153
Epoch 44/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1775 - accuracy: 0.9157
Epoch 45/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1774 - accuracy: 0.9155
Epoch 46/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1773 - accuracy: 0.9156
Epoch 47/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1772 - accuracy: 0.9163
Epoch 48/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1771 - accuracy: 0.9168
Epoch 49/100
966/966 [==============================] - 3s 3ms/step - loss: 0.1771 - accuracy: 0.9151
Epoch 50/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1769 - accuracy: 0.9163
Epoch 51/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1767 - accuracy: 0.9164
Epoch 52/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1766 - accuracy: 0.9162
Epoch 53/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1768 - accuracy: 0.9161
Epoch 54/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1766 - accuracy: 0.9161
Epoch 55/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1763 - accuracy: 0.9157
Epoch 56/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1766 - accuracy: 0.9167
Epoch 57/100
966/966 [==============================] - 3s 3ms/step - loss: 0.1763 - accuracy: 0.9162
Epoch 58/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1763 - accuracy: 0.9165
Epoch 59/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1760 - accuracy: 0.9162
Epoch 60/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1761 - accuracy: 0.9166
Epoch 61/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1762 - accuracy: 0.9164
Epoch 62/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1762 - accuracy: 0.9169
Epoch 63/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1757 - accuracy: 0.9153
Epoch 64/100
966/966 [==============================] - 3s 3ms/step - loss: 0.1758 - accuracy: 0.9164
Epoch 65/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1756 - accuracy: 0.9165
Epoch 66/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1756 - accuracy: 0.9162
Epoch 67/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1755 - accuracy: 0.9164
Epoch 68/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1756 - accuracy: 0.9163
Epoch 69/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1753 - accuracy: 0.9169
Epoch 70/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1755 - accuracy: 0.9170
Epoch 71/100
966/966 [==============================] - 3s 3ms/step - loss: 0.1755 - accuracy: 0.9166
Epoch 72/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1755 - accuracy: 0.9168
Epoch 73/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1753 - accuracy: 0.9161
Epoch 74/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1754 - accuracy: 0.9165
Epoch 75/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1751 - accuracy: 0.9164
Epoch 76/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1754 - accuracy: 0.9162
Epoch 77/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1753 - accuracy: 0.9158
Epoch 78/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1753 - accuracy: 0.9164
Epoch 79/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1753 - accuracy: 0.9166
Epoch 80/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1751 - accuracy: 0.9159
Epoch 81/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1752 - accuracy: 0.9173
Epoch 82/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1751 - accuracy: 0.9167
Epoch 83/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1750 - accuracy: 0.9166
Epoch 84/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1750 - accuracy: 0.9166
Epoch 85/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1751 - accuracy: 0.9162
Epoch 86/100
966/966 [==============================] - 3s 3ms/step - loss: 0.1749 - accuracy: 0.9167
Epoch 87/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1750 - accuracy: 0.9167
Epoch 88/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1748 - accuracy: 0.9166
Epoch 89/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1749 - accuracy: 0.9166
Epoch 90/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1749 - accuracy: 0.9161
Epoch 91/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1747 - accuracy: 0.9164
Epoch 92/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1748 - accuracy: 0.9170
Epoch 93/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1746 - accuracy: 0.9168
Epoch 94/100
966/966 [==============================] - 3s 3ms/step - loss: 0.1748 - accuracy: 0.9164
Epoch 95/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1745 - accuracy: 0.9170
Epoch 96/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1744 - accuracy: 0.9168
Epoch 97/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1747 - accuracy: 0.9160
Epoch 98/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1747 - accuracy: 0.9163
Epoch 99/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1747 - accuracy: 0.9169
Epoch 100/100
966/966 [==============================] - 2s 2ms/step - loss: 0.1745 - accuracy: 0.9165

In [31]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

322/322 - 1s - loss: 0.1809 - accuracy: 0.9165 - 764ms/epoch - 2ms/step
Loss: 0.18093067407608032, Accuracy: 0.916480541229248

In [32]:
# Export our model to HDF5 file
nn.save("optimization.h5")

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(